---
driver:
  name: docker 
  socket: <%= ENV['DOCKER_HOST'] %>
driver_config:
  require_chef_omnibus: true
busser:
  sudo: true

platforms:
  - name: centos-6.4
    driver_config:
      image: ryuzee/centos_chef:6.4

suites:
- name: default
  run_list: 
    - sensu-server-wrapper::default
    - sensu-client-wrapper::default
  attributes:
    sensu:
      use_ssl: false
    sensu-server-wrapper:
      iptables_enabled: false
    sensu-client-wrapper:
      name: hoge
      ipaddress: 127.0.0.1
      roles: ["bar"]

